import Head from "next/head";
import React, { FC, useEffect, useRef } from "react";
import styles from "../styles/Gsap.module.scss";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import Image from "next/image";
gsap.registerPlugin(ScrollTrigger);

const GsapAnimation: FC = () => {
  const mainRef = useRef<HTMLElement | null>(null);
  const panelsWrapperRef = useRef<HTMLDivElement | null>(null);
  const panelsRef = useRef<HTMLDivElement | null>(null);
  const didEffect = useRef(false);

  useEffect(() => {
    if (didEffect.current) return;
    didEffect.current = true;
    const panelsElement = panelsRef?.current;
    if (!panelsElement) return;
    const panelsWrapperElement = panelsWrapperRef?.current;
    if (!panelsWrapperElement) return;
    setupGsap(panelsElement, panelsWrapperElement);
    // if (!mainRef) return;
  }, []);
  const setupGsap = (
    panelsElement: HTMLDivElement,
    panelsWrapperElement: HTMLDivElement
  ) => {
    gsap.to(panelsElement, {
      x: () => -(panelsElement.clientWidth - panelsWrapperElement.clientWidth),
      ease: "none",
      scrollTrigger: {
        trigger: "#horizontal-scroll-section",
        start: "top top",
        end: () =>
          `+=${panelsElement.clientWidth - panelsWrapperElement.clientWidth}`,
        scrub: true,
        pin: true,
        anticipatePin: 1,
        invalidateOnRefresh: true,
        markers: true,
      },
    });
  };
  return (
    <>
      <main className={styles.main}>
        <Head>
          <title>GSAP Scroll Animation</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className={styles.section} id="horizontal-scroll-section">
          <div className={styles.container}>
            <div className={styles.panelsWrapper} ref={panelsWrapperRef}>
              <div className={styles.panels} ref={panelsRef} id="panels">
                <div className={styles.panel}>
                  <Image
                    src="https://placekitten.com/g/1440/960"
                    width={1440}
                    height={960}
                    alt=""
                    className={styles.image}
                  />
                </div>
                <div className={styles.panel}>テキストテキスト</div>
                <div className={styles.panel}>
                  <Image
                    src="https://placekitten.com/g/1440/960"
                    width={1440}
                    height={960}
                    alt=""
                    className={styles.image}
                  />
                </div>
                <div className={styles.panel}>
                  <Image
                    src="https://placekitten.com/g/1440/960"
                    width={1440}
                    height={960}
                    alt=""
                    className={styles.image}
                  />
                </div>
                <div className={styles.panel}>
                  <Image
                    src="https://placekitten.com/g/1440/960"
                    width={1440}
                    height={960}
                    alt=""
                    className={styles.image}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className={styles.footer}></footer>
    </>
  );
};

export default GsapAnimation;
